### ISSUE TITLE
Thread abort is not supported on this platform

### ISSUE THREAD

**Issue by vesuvian** [JTrotta/RaspberrySharp#16]
I'm doing some .Net Core programming using the current latest RaspberrySharp nuget package and running on a Raspberry Pi 3B v1.2.

I've been able to get digital-in pins working perfectly, but I can't for the life of me get digital-out working.

```
private GpioConnection m_Connection;

public void SetDigitalOut(bool digitalOut)
{
	if (digitalOut)
		m_Connection.Close();
	else
		m_Connection.Open();
}
```

On `Close()` I'm getting the following exception:

```
PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort()
   at RaspberrySharp.System.Timers.HighResolutionTimer.Stop()
   at RaspberrySharp.IO.GeneralPurpose.GpioConnection.Close()
```

Does the HighResolutionTimer need to make use of cancellation tokens to be fully supported by .Net Core?

**Comment by JTrotta** [comment]
Fixed.
