### ISSUE TITLE
How to blink activity LED on the Raspberry Pi Zero?

### ISSUE THREAD

**Issue by rgelb** [JTrotta/RaspberrySharp#22]
According to this [thread](https://www.raspberrypi.org/forums/viewtopic.php?t=194262), on the Raspberry Pi Zero the Activity LED is on GPIO Pin 47.

I am looking at \RaspberrySharp\IO\GeneralPurpose\ProcessorPin.cs and I don't see an enumeration for Pin 47.  They end at 45.

Is there a way to blink the LED with this library?

**Comment by JTrotta** [comment]
I suppose PI ZERO does not have GPIO 47. 
Did you try  GPIO 17?
