### ISSUE TITLE
GPIO.GeneralPurpose and pin numbering - example is confusing

### ISSUE THREAD

**Issue by pmeloy** [JTrotta/RaspberrySharp#23]
I'm trying to figure out how to twiddle pins by looking at the blink and watch examples. In the project description it says that only one pin numbering system is in use which I took to mean BCM. The watch example usage shows "Console.WriteLine("I.e.: sudo mono Test.Gpio.WatchPin.exe P1Pin23");"

What is a PiPin23? Is that pin #23 on the header or is it GPIO23?

Also, forgive my newbishness but is there a simpler way of passing the pin number to the program rather than using a string and having to search an enumeration? Can't we just give the number and go from there?

**Comment by JTrotta** [comment]
There are some misprint. Have look here:
[GPIOMonitor](https://github.com/JTrotta/RaspberrySharp/blob/master/Samples/Monitors/GpioMonitor/Program.cs)

We only use GPIO numbers.
