### ISSUE TITLE
New to RaspberrySharp

### ISSUE THREAD

**Issue by HansR00** [JTrotta/RaspberrySharp#28]
I just started/made my first project with RaspberrySharp on a RPi 3b+ and am happy with this library. It took me several months (not continuously) to try different libraries - there are not many - and to decide for RaspberrySharp with its easy to handle interface and despite its lack of documentation. The code explains itself pretty well and for somebody new to the GPIO but not totally new to coding, it is easy to read and to understand. I use C# with NET Core 3.1 C# is my standard development environment and I would like to keep the distance to the actual registers as high as possible. RaspberrySharp seems to accomplish that.

I implemented a Plantower PMS1003 on the serial port and a SHT31 temp/humidity sensor on the i2c interface. That went smooth although I do have a problem with reinitialising the SHT31 when the program exits (through a kill) and restarts. It seems I need a hardware reset (re-power the sensor) to start reading again. I have to look into that  one.

So far: thank you and I will dig deeper into the different possibilities to use more sensors and create a true sensor array. Including hopefully some gas sensors which require A/D converters

As the last comments issues are from 2018 can you tell me what the status is of this  project?
Is it still under development / maintained / being looked after? Are there other projects with this lib?

**Comment by JTrotta** [comment]
We are now working with MS to the new [IOT ](https://github.com/dotnet/iot) library. When the new library will work as expected, this one will become obsolete.

**Comment by HansR00** [comment]
OK, thanks. Will we  be notified some way?
A pity though... Took me some work to get where I am now. :D
Would that library have the same possibilities? All  interfaces (Serial,
i2c etc... ) easily accessible?

Cheers, Hans



Op zo 23 aug. 2020 om 19:44 schreef Gerardo <notifications@github.com>:

**Comment by JTrotta** [comment]
Yes. At least we hope!
But don't be afraid. Basically buses (i2c SPI, Serial etc.) work always in the same way. When you will be skilled about them, you will be able to use them with whatever library.
