### ISSUE TITLE
Can´t load RaspberrySharp.csproj in VS2015

### ISSUE THREAD

**Issue by moelski** [JTrotta/RaspberrySharp#3]
Hi !

Seems to me that there is a problem in the RaspberrySharp.csproj project file. 
My VS2015 reports the following: 
![vs2015](https://user-images.githubusercontent.com/17078960/37582446-ddd4315e-2b44-11e8-8de2-5bb5da186dd7.png)

Can you fix that in order to load the pßroject properly? 

Dominik

**Comment by JTrotta** [comment]
Sorry, you cannot use VS2015. Only VS 2017.
JJ
