### ISSUE TITLE
First GPIO Test failed

### ISSUE THREAD

**Issue by moelski** [JTrotta/RaspberrySharp#4]
Hi !

Just did a very basic test - switching an LED with GPIO 18. 
```
namespace TestGPIO
{
    using System;
    using System.Linq;
    using System.Threading;

    using RaspberrySharp.IO.GeneralPurpose;

    class Program
    {
        private static GpioConnection conPin;

        static void Main(string[] args)
        {
            conPin = new GpioConnection(ProcessorPin.Gpio18.Output());

            Console.WriteLine("LED On");

            conPin.Pins.First().Toggle();
            Console.WriteLine(conPin.Pins.First().Configuration.Pin);

            Thread.Sleep(1000);

            Console.WriteLine("LED Off");
            conPin.Pins.First().Toggle();
            Thread.Sleep(1000);

            Environment.Exit(0);
        }
    }
}
```

But nothing happens. It did also not work with your "Demo" application. 

Did I miss something or is there a bug in the lib? 

btw. I´m using an Raspberry Pi Zero (no W). 

Dominik

**Comment by moelski** [comment]
Using the FileGpioConnectionDriver did work ... 
```
            outp = ProcessorPin.Gpio22.Output();
            var ts = new GpioConnectionSettings
            {
                Driver = new FileGpioConnectionDriver()
            };

            conPin = new GpioConnection(ts);
            conPin.Add(outp);
```

**Comment by moelski** [comment]
Hi gerardo, 
did you see a chance to test this topic at this weekend. 
This bug is some kind of "show stopper" ... 

Dominik

**Comment by JTrotta** [comment]
I can have a check this afternoon. But cannot test it on RPI.

**Comment by moelski** [comment]
Great. I have all kinds of Pi here. So testing would be not a big deal :-)

**Comment by JTrotta** [comment]
Just created a develop branch where we can make any kind of test before release it.
About this bug: what you see in logger? which RPI you are testing it on?
Did you test it using "sudo" rights?
I remember (but I can be wrong) the on CM3 it worked.
JJ

**Comment by moelski** [comment]
> which RPI you are testing it on?

Last Test was with the new Pi 3 B+. Maybe that´s the "problem" ?

> Did you test it using "sudo" rights?

for sure

will test with a Pi Zero und Pi 2 / 3.

**Comment by JTrotta** [comment]
The problem should be here:
```
        public void Write(ProcessorPin pin, bool value)
        {
            int shift, offset;
            IntPtr pinGroupAddress;
            if ((int)pin < 32)
            {
                offset = Math.DivRem((int)pin, 32, out shift);
                pinGroupAddress = gpioAddress + (int)((value ? OP.BCM2835_GPSET0 : OP.BCM2835_GPCLR0) + offset);
            }
            else
            {
                offset = Math.DivRem((int)pin - 32, 32, out shift); // to use gpio >= 32 
                pinGroupAddress = gpioAddress + (int)((value ? OP.BCM2835_GPSET1 : OP.BCM2835_GPCLR1) + offset);
            }

            SafeWriteUInt32(pinGroupAddress, (uint)1 << shift);
        }
```

But I'm quite sure that on my CM3 this code works. CM3 has a second set (GPSET1) where are GPIO with number > 32. May be that there is some address mistake in OP.cs 
OP.cs is the common address repository used by all drivers and bus. 
But to check it I need a RPI connected.
You can add  a Trace or Console write just after this row:
`pinGroupAddress = gpioAddress + (int)((value ? OP.BCM2835_GPSET0 : OP.BCM2835_GPCLR0) + offset);`
to check if anything goes wrong.
JJ

**Comment by moelski** [comment]
I added this in "GpioConnectionDriver.cs"

```
            if ((int)pin < 32)
            {
                offset = Math.DivRem((int)pin, 32, out shift);
                pinGroupAddress = gpioAddress + (int)((value ? OP.BCM2835_GPSET0 : OP.BCM2835_GPCLR0) + offset);
                Console.WriteLine($"Write Done GPIO offset:{offset} pinGroupAddress:{pinGroupAddress.ToString("X8")}");
            }
```
And it seems to run: 

> Blink Sample
> ===============
> GPIO : Gpio18
> LED On
> Write Done GPIO offset:0 pinGroupAddress:76F0701C
> LED Off
> Write Done GPIO offset:0 pinGroupAddress:76F07028
> LED On

At the Pi 3 B+ it works. 

But testing on the Zero (not W) did not. It seems to run but the LED stays dark. 

> Blink Sample
> ===============
> GPIO : Gpio18
> Bcm2835
> LED On
> Write Done GPIO offset:0 pinGroupAddress:B6F8501C
> LED Off
> Write Done GPIO offset:0 pinGroupAddress:B6F85028
> LED On
> Write Done GPIO offset:0 pinGroupAddress:B6F8501C
> LED Off

Is that correct that the pinGroupAddress is different?

**Comment by moelski** [comment]
btw ... I made a simple test to ensure that the LED is wired correctly: 
```
pi@raspberrypi ~ $ gpio export 18 out
pi@raspberrypi ~ $ gpio -g write 18 1 
pi@raspberrypi ~ $ gpio -g write 18 0
```
from here http://raspberrypiguide.de/howtos/raspberry-pi-gpio-how-to/

**Comment by JTrotta** [comment]
> Is that correct that the pinGroupAddress is different?

Yes it is. The question is to check if they are correct. I do not have Zero processor specification. We have to find documentation about it.
Do not use gpio command to export/ read or write, because you change them during mono process. Just check if mono created the right file and if it put 0 (=false) or 1 (=true) in it: it should be here : /sys/class/gpio/{gpio number}/value

**Comment by moelski** [comment]
Hi, 
can do some more Test this evening. 

But what confuses me is that it works with the "old" Raspberry Sharp lib.

**Comment by JTrotta** [comment]
OK.
Just make a recap:
On which RP it does not work? 
If are Zeros, we have to check OP.cs 
If All Pis, we are missing something else.
But in any case it wold be easy to solve.
JJ

**Comment by moelski** [comment]
At the moment it is the Pi Zero. I can test it with a Pi Zero W this evening. 
Pi 3 B+ works.

**Comment by JTrotta** [comment]
Ok. Indeed I tested it only on pi1, p2 p3 and cm3. I'm going to buy Zeros.
In the meanwhile we can make some test on yours. First we need to check which driver is selected by the old raspberry sharp library, when running on zero.

**Comment by moelski** [comment]
Ok here are my results so far... The tests run on an "old" Pi Zero without Wifi

The Pi is fresh rebooted and so there are no gpio files: 
```
pi@PiRoboter:/sys/class/gpio $ ls
export  gpiochip0  unexport
pi@PiRoboter:/sys/class/gpio $
```
I´ve created two demo applications. Both use the same Blink Code as in the sample Blink. The demo with the **old lib** is compiled using Visual Studio 2015, the **new one** is compiled using VS 2017. But I think that makes no real difference at all. 

If I run the NEW code I get this output: 

```
pi@PiRoboter:~/sources/testold $ sudo mono Blink.exe
Use GpioConnectionDriver
Use MemoryGpioConnectionDriver
Use FileGpioConnectionDriver
Write Done GPIO offset:0 pinGroupAddress:B6F03028
Blink Sample
===============
GPIO : Gpio18
Bcm2835
LED On
Write Done GPIO offset:0 pinGroupAddress:B6F0301C
LED Off
Write Done GPIO offset:0 pinGroupAddress:B6F03028
LED On
Write Done GPIO offset:0 pinGroupAddress:B6F0301C
LED Off
Write Done GPIO offset:0 pinGroupAddress:B6F03028
```
The LED **did not blink** !!

checking /sys/class shows the GPIO Pin: 
```
pi@PiRoboter:/sys/class/gpio $ ls
export  gpio18  gpiochip0  unexport
```

Now running the Code with the **old lib** :
```
pi@PiRoboter:/sys/class/gpio/gpio18 $ sudo mono ~/sources/testold/BlinkOld.exe
Use GpioConnectionDriver
Use MemoryGpioConnectionDriver
Use FileGpioConnectionDriver
Write Done GPIO offset:0 pinGroupAddress:B6F0C028
Blink Sample
===============
GPIO : Pin18
LED On
Write Done GPIO offset:0 pinGroupAddress:B6F0C01C
LED Off
Write Done GPIO offset:0 pinGroupAddress:B6F0C028
LED On
Write Done GPIO offset:0 pinGroupAddress:B6F0C01C
```
The LED goes on and off as expected !

And now the results: **Both use the GpioConnectionDriver.**
But the pinGroupAddress is different: 
OLD : ON : B6F0**C**01C, OFF : B6F0**C**028
NEW : ON : B6F0**3**01C, OFF : B6F0**3**028

I think this is our problem ? 

Dominik

**Comment by moelski** [comment]
Oh and one other thing ... 

The new Lib returns this for **GetProcessorBaseAddress**
Bcm2835 -> 1059061760 (Base address)

The old Lib returns this for **GetProcessorBaseAddress**
Bcm2708 -> 538968064 (Base address)

Hmm did we have a board detection problem in general ? 

Maybe there should be a better board detection like this one: 
https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-obtain_hw_model#L125-L364 
?

This would be a good reference, too: 
https://github.com/AndrewFromMelbourne/raspberry_pi_revision

**Comment by JTrotta** [comment]
Great work.
You got it.

**Comment by moelski** [comment]
Will you create a fix for that?
And what do you think about better board detection?

**Comment by JTrotta** [comment]
Yes of course. Gonna try just this morning.
I think board detection works. This is just a bug due to the fact we do not use pi zero.

**Comment by JTrotta** [comment]
I need your help, because do not have Pi Zero yet.
Have a look here at the file Board.cs:
```        public Processor Processor
        {
            get
            {
                Processor processor;
                return Enum.TryParse(ProcessorName, true, out processor) 
                             ? processor : Processor.Unknown;
            }
        }
```
Here we define the right PI, reading some data from PI here: `private static Board LoadBoard()`

So you may read data coming from PI in LoadBoard(), then we can check why we map the processor to Bcm2835 (this is the new processor of PI3 and CM3) and not the probably the right one Bcm2708.
The right model is identified here : `LoadModel()` using this formula:
`(firmware & 0xFFFF)` where firmware is loaded here: `public int Firmware`

Thank you
JJ

**Comment by JTrotta** [comment]
this link seems updated:

> Maybe there should be a better board detection like this one:
https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-obtain_hw_model#L125-L364
?

I will remap model using these information.  But now let's check why zero is not mapped to 0x92,

Thank you
JJ

**Comment by moelski** [comment]
I will do some tests this evening. Have no Pi Zero in access right now. 

> I will remap model using these information.

Maybe it`s also a good idea to add some basic Logging to the lib - especially on those methods like detecting the board. But I think this is a new issue :-)

**Comment by moelski** [comment]
Maybe this still helps ... I got access via SSH to my Pi Zero :-)

And all the board stuff is extracted from /proc/cpuinfo. 

And here it is for my Pi Zero:
```
pi@PiRoboter:~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 997.08
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 900093
Serial		: 0000000057e62cd2
```

If you add 0xFFFF to the Revision it results in 0x0093 ... not 0x0092.

**Comment by JTrotta** [comment]
Ok. 0x92 or 0x93 are both recognized as pi zero. And the BCM seems to be a 2835. But I remember that 2835 should be mapped as 2708. 
Moreover, we still have methods to detect the board, the host app could call static methods to read data.
Today will  check why 2835 must be mapped as 2708 for pizero

**Comment by moelski** [comment]
Look here: https://wiki.openwrt.org/toh/raspberry_pi_foundation/raspberry_pi

The SoC is BCM2835 and the Family is BCM2708. 

When I remember correctly the Zero uses the same SoC as the Pi 1 / 2.

**Comment by JTrotta** [comment]
Yes, I got some trouble about that some years ago. If so, it's very easy to assign to 092/093 the bcm2708. I cannot do it now, but you can play by yourself in develop branch.

**Comment by moelski** [comment]
I looked into my old code and found the property 

`public string ProcessorName`

And in my old lib code I changed the getter because I had similar problems when the Pi Zero came out ... 

This is what I used in the past: 
```
        public string ProcessorName
        {
            get
            {
                // Console.WriteLine("DEBUG : " + Model);
                // https://wiki.openwrt.org/toh/raspberry_pi_foundation/raspberry_pi
                switch (Model)
                {
                    case Model.A: return "BCM2708";
                    case Model.APlus: return "BCM2708";
                    case Model.BRev1: return "BCM2708";
                    case Model.BRev2: return "BCM2708";
                    case Model.BPlus: return "BCM2708";
                    case Model.ComputeModule: return "BCM2708";
                    case Model.B2: return "BCM2709";
                    case Model.Zero: return "BCM2708";
                    case Model.ZeroW: return "BCM2708";
                    case Model.B3: return "BCM2709";  // BCM2710
                    case Model.B3Plus: return "BCM2709";
                    default: return "UNKNOWN";
                }
            }
        }
```

And what should I say ... **The LED blinks fine** :-)

**_EDIT:_** 
This is also not completely true ... Since B3 and B3+ have BCM2710 according to this list: 
https://wiki.openwrt.org/toh/raspberry_pi_foundation/raspberry_pi
But I assume that the base address is the same ...

**Comment by JTrotta** [comment]
Ok.
So are you changing develop branch to map BCM2708 to PiZero, or you want me to do that?
We should organize to avoid doing things twice.
Thank you

**Comment by moelski** [comment]
I'm on a business trip until tomorrow. Would be great if you do the merge.
Thx
