### ISSUE TITLE
How did you develop for Raspberry Pi?

### ISSUE THREAD

**Issue by moelski** [JTrotta/RaspberrySharp#8]
Hi Gerardo, 

this is not really in issue more a question of interest.. 

How are you developing .net for the Raspberry Pi. The normal way is to use Visual Studio on Windows and place the binaries on the pi. But debugging is a little pain with that scenario. 

I tried to compile MonoDevelop 7.x for the Pi, but unfortunately it didn't work. MonoDevelop would be nice because of the Remote Debugging feature ... 

So what's your way of coding and debugging? 

Dominik

**Comment by JTrotta** [comment]
Ok. You do not need mono develop at all. Compile on your pc. Just install mono on raspberry, always keep it updated, just copy and paste libraries and exe. It will work.

**Comment by moelski** [comment]
That's the way I do it :-)
The problem is you have no chance for debugging (stepping through the code, check variables, etc).

**Comment by JTrotta** [comment]
Install remote debugger plugin in Vs17 and remote debug server on do I. It will work

**Comment by JTrotta** [comment]
Install remote debugger plugin in Vs17 and remote debug server on rpi. It will work

**Comment by moelski** [comment]
Du you have a link for the plugin / server? 
Or is there anywhere a tutorial for the first steps?

**Comment by JTrotta** [comment]
https://marketplace.visualstudio.com/items?itemName=Bongho.MonoRemoteDebugger

**Comment by moelski** [comment]
That´s awesome !
It lacks in some scenarios, but overall it´s great. 

Anyway ... MonoDevelop would be a Solution, too. 
Will try to compile the new one for Windows ...

**Comment by JTrotta** [comment]
If the project is not big and simple, yes you can use monodevelop with no problems. As soon as the project grows, the only way is to use VS and fulfill the code with logs.
